config/routes.rb
Rails.application.routes.draw do
  resources :menu_items

  get '/menu' => 'pages#menu'
  root 'pages#home'

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @menu_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @menu_item }
      else
        format.html { render action: 'edit' }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_item_params
      params.require(:menu_item).permit(:number, :name, :price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def menu
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bill Printer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class='container'>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <i class="fa fa-print"></i>
          Bill Printer
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="main-nav-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Menu Items", menu_items_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>


</body>
</html>

app/views/menu_items/_form.html.erb
<%= form_for(@menu_item) do |f| %>
  <% if @menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
      <% @menu_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h1>Editing Menu Item</h1>
        <div class="well">
            <%= render 'form' %>
            
            <!--<%= link_to 'Show', @menu_item %> |-->
            <%= link_to 'Back', menu_items_path %>
        </div>
    </div>
</div>

app/views/menu_items/index.html.erb
<h1>Listing Menu Items</h1>

<table class="table">
  <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.number %></td>
        <td><%= menu_item.name %></td>
        <td><%= menu_item.price %></td>
        <td><%= link_to 'View', menu_item, class: 'btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_menu_item_path(menu_item), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Delete', menu_item, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu item', new_menu_item_path, class: 'btn btn-primary' %>

app/views/menu_items/new.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h1>New Menu Item</h1>
        <div class="well">
            <%= render 'form' %>

            <%= link_to 'Back', menu_items_path %>
        </div>
    </div>
</div>

app/views/menu_items/show.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
      <p class="alert alert-success"><%= notice %></p>

      <p>
        <strong>Number:</strong>
        <%= @menu_item.number %>
      </p>
      
      <p>
        <strong>Name:</strong>
        <%= @menu_item.name %>
      </p>
      
      <p>
        <strong>Price:</strong>
        <%= @menu_item.price %>
      </p>
      
      <%= link_to 'Edit', edit_menu_item_path(@menu_item) %> |
      <%= link_to 'Back', menu_items_path %>
    </div>
</div>

app/views/pages/home.html.erb
<h2>Home</h2>
Where we will be able to add items to a new bill and hit print!

app/views/pages/menu.html.erb
<h2>Menu Page</h2>
<p>Where you can view and add items to menu.</p>